### PR TITLE
Different background preview style

### PR DESCRIPTION
**Pull request by metakirby5**
This is what I meant by my original suggestion for background images. Play around with it and see if you like it :)

Here's an image of what it looks like:
preview

### CODE REVIEW

**Comment by 97-109-107** [comment]
Thanks!

**Comment by 97-109-107** [comment]
There's something I didn't notice - the background color that will be used in my terminals is now less apparent, because all yamls without a wallpaper have the same color. This makes the initial 'scanning' for the right color a bit more difficult.

Could you suggest ways of keeping your full-tile background preview and my previous tile-background color?

new
new

old
old

**Comment by metakirby5** [comment]
I'm currently using the method described [here](https://css-tricks.com/tinted-images-multiple-backgrounds/) to add the background tint. If you can transform the background color to rgba, you can template it in and make the tint change with the background color.

P.S. As you can see, the background/foreground colors aren't properly detecting for me. I'll open up an issue about it.

**Comment by 97-109-107** [comment]
Fixed with fff6b68

**Pull request merged**
